# Generated by Django 3.1.3 on 2020-11-11 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201111_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATname', models.CharField(max_length=50, verbose_name='category name')),
                ('CATdesc', models.TextField(max_length=1000, verbose_name='category descereption')),
                ('CATimage', models.ImageField(upload_to='category/', verbose_name='category image')),
                ('CATpearent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
    ]
