# Generated by Django 3.1.3 on 2020-11-11 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201111_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Accessoris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PACCAlternative', models.ManyToManyField(related_name='alternativeACCESSORS_products', to='product.Product')),
                ('PACCproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainACCESSORS_product', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Accessoris',
                'verbose_name_plural': 'Product Accessoris',
            },
        ),
    ]
