# Generated by Django 3.1.3 on 2020-11-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20201112_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDimag',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Image'),
        ),
    ]
