# Generated by Django 3.1.3 on 2020-11-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_prdslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDdiscounetPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='product discounte'),
            preserve_default=False,
        ),
    ]
