# Generated by Django 3.1.3 on 2020-11-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_prddiscounetprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDBestsaler',
            field=models.BooleanField(default=1, verbose_name='product bestsaler'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='PRDIsnew',
            field=models.BooleanField(blank=True, default=1, verbose_name='product new'),
            preserve_default=False,
        ),
    ]
